name: Update Docs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"  # Run every week on Sunday at midnight UTC to refresh docs.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - name: "Install dependencies"
      run: |
        sudo apt-get update && sudo apt-get install graphviz texmaker

    - name: "Checkout" 
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@edge
      with:
        doxyfile-path: "./Doxyfile"
        additional-packages: graphviz
                             biblatex
        enable-latex: true
    
    - name: Create folder
      run: |
        mkdir -p zipped_docs

    - name: Zip docs
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r zipped_docs/docs.zip ./docs
  
    - name: Upload doxygen artifact
      uses: actions/upload-artifact@v2
      with:
        name: Doxygen docs
        path: zipped_docs
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download doxygen artifact
      uses: actions/download-artifact@v2
      with:
        name: Doxygen docs
        path: zipped_docs

    - name: Unzip docs
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq zipped_docs/docs.zip -d .

    - name: Deploy
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/reference
